[workspace]
resolver = "3"
members = [ 
    "common",
    "nss-keycloak",
    "pam-keycloak",
]

[workspace.package]
version = "0.2.0"
publish = false
license = "MIT"
authors = [
    "Lily Hopkins <lily@hpkns.uk>",
]
